export enum InvitationStatus {
    CREATED = 'CREADA', // ENVIADA
    SENT = 'ENVIADA', // ENVIADA
    PENDING = 'PENDIENTE DE CONFIRMACIÓN', // PENDIENTE
    ATTENDANCE_CONFIRMED = 'ASISTENCIA CONFIRMADA', // ASISTENCIA_CONFIRMADA
    SCANNED = 'SCANNED', // ESCANEO_CONFIRMADO
  }
  